global:
  scrape_interval:     15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["nodeexporter:9100"]

  - job_name: "process"
    static_configs:
      - targets: ["processexporter:9256"]

  - job_name: "farm-proxy"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["172.17.0.1:8080"]

